### PR TITLE
update _bedtools

### PR DESCRIPTION
**Pull request by cgjosephlee**
Add some subcommands.

### CODE REVIEW

**Comment by kloetzl** [comment]
Hi, thanks for your work. I have just added contributing guidelines to the repo. Please rebase your commit on this new master and update accordingly. 👍

**Comment by cgjosephlee** [comment]
I have rebased the commits according to the guides!

**Comment by kloetzl** [comment]
Thank you for the changes. Note that your terminal may be wider than mine which cuts of completion hints at some point. In the case of `-wo` and `-wao` they are indistinguishable. Please shorten the text where appropriate.

bedtools

**Comment by cgjosephlee** [comment]
> Thank you for the changes. Note that your terminal may be wider than mine which cuts of completion hints at some point. In the case of `-wo` and `-wao` they are indistinguishable. Please shorten the text where appropriate.

I'm not an English native speaker. It is hard to shorten the sentences and make them different, do you have any idea?

**Comment by kloetzl** [comment]
> I'm not an English native speaker.

Neither am I. :man_shrugging:

Here is an idea. For `-wao` we could just emphasize the difference and leave `-wo` as it is.

`Like -wo but uses dummy entry for A features without an overlap in B`.

What do you think?

**Comment by cgjosephlee** [comment]
This is a good idea, but `-wo` is still too long to display. Is our goal to only make them distinguishable?

**Pull request closed without merging**
